name: Build

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Push Docker Image
        uses: Dwolla/jenkins-agents-workflow/.github/actions/build@main
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BASE_TAG: 4.13.2-1-jdk11-e720044-bd26540
          TAG_NAME: PYTHON_TAG
          IMAGE_NAME: dwolla/jenkins-agent-ansible-packer
  build-complete:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The build completed successfully"
